import images from "./images";

export const onboarding = [
  {
    id: 1,
    title: "Escape form the outside loud and enter your Reading Corner!",
    description: "Let's start reading 📙.",
    image: images.onboarding1,
  },
  {
    id: 2,
    title: "Discover yourself",
    description: "Look at yourself in a different way in your Reading Corner.",
    image: images.onboarding2,
  },
  {
    id: 3,
    title: "Let's read!",
    description: "Enter your Book, browse, and read.",
    image: images.onboarding3,
  },
];

export const books = [
  {
    id: 1,
    title: "Pencil",
    author: "Laurence Ashraf",
    image: require("@/assets/images/book1.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "Pencil is a thrilling mystery novel that keeps readers on the edge of their seats. Laurence Ashraf masterfully weaves a tale of suspense and intrigue.",
    ISBN: "978-1234567891",
    publisher: "Mystery House",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://drive.google.com/file/d/1rtnWmZpzu3kfba-BEBXaGYgiGFKULBgt/view?usp=drive_link",
    price: 20,
  },
  {
    id: 2,
    title: "Walk into the shadow",
    author: "Jane Doe",
    image: require("@/assets/images/book2.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "Walk into the shadow is an inspiring self-help book that guides readers through overcoming their fears and embracing their true potential. Jane Doe provides practical advice and motivational insights.",
    ISBN: "978-0987654324",
    publisher: "Inspiration Press",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://example.com/book2",
    price: 20,
  },
  {
    id: 3,
    title: "Window Blown Shadows",
    author: "Laurence Ashraf",
    image: require("@/assets/images/book3.jpg"),
    language: "English",
    category: "Science Fiction",
    description:
      "Window Blown Shadows is a fascinating science fiction story that explores the boundaries of reality and imagination. Laurence Ashraf takes readers on an unforgettable journey through time and space.",
    ISBN: "978-1122334459",
    publisher: "Galactic Press",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://example.com/book3",
    price: 20,
  },
  {
    id: 4,
    title: "The secret garden",
    author: "Emily Brown",
    image: require("@/assets/images/book5.jpeg"),
    description:
      "In a house full of sadness and secrets, can young, orphaned Mary find happiness Mary Lennox, a spoiled, ill-tempered, and unhealthy child, comes to live with her reclusive uncle in Misselthwaite Manor on England’s Yorkshire moors after the death of her parents. There she meets a hearty housekeeper and her spirited brother, a dour gardener, a cheerful robin, and her wilful, hysterical, and sickly cousin, Master Colin, whose wails she hears echoing through the house at night. With the help of the robin, Mary finds the door to a secret garden, neglected and hidden for years. When she decides to restore the garden in secret, the story becomes a charming journey into the places of the heart, where faith restores health, flowers refresh the spirit, and the magic of the garden, coming to life anew, brings health to Colin and happiness to Mary.",
    language: "English",
    category: "Children's Book",
    ISBN: "9780517189603 (ISBN10: 0517189607)",
    publisher: "Fredrick A. Stokes Company",
    publishingNumber: "1st Edition",
    publishingYear: 1911,
    url: "https://drive.google.com/file/d/1rtnWmZpzu3kfba-BEBXaGYgiGFKULBgt/view?usp=drive_link",
    price: 20,
  },
  {
    id: 5,
    title: "Mother Island",
    author: "Jamie Figueroa",
    image: require("@/assets/images/motherisland.png"),
    language: "English",
    category: "Drama",
    description:
      "Mother Island is a poetic and evocative narrative that delves into themes of identity, belonging, and the unbreakable bonds of family. Through vivid storytelling and heartfelt emotion, Jamie Figueroa presents a story of a daughter's journey to reclaim her heritage and find her true self.",
    ISBN: "978-1234567890",
    publisher: "Azure Horizon Press",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://drive.google.com/file/d/1rtnWmZpzu3kfba-BEBXaGYgiGFKULBgt/view?usp=drive_link",
    price: 20,
  },
  {
    id: 6,
    title: "Glittering a Turd",
    author: "Sarah Davis",
    image: require("@/assets/images/book6.jpg"),
    language: "English",
    category: "Romance",
    description:
      "Glittering a Turd is a heartwarming romance novel that explores the complexities of love and relationships. Sarah Davis crafts a touching narrative that will resonate with readers.",
    ISBN: "978-0987654323",
    publisher: "Romance Reads Press",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://example.com/book6",
    price: 20,
  },
  {
    id: 7,
    title: "A Family's Tale",
    author: "Jamie Figueroa",
    image: require("@/assets/images/a family's tale.jpeg"),
    language: "English",
    category: "Family",
    description:
      "A Family's Tale is a heartwarming story that celebrates unity, unconditional love, and the enduring strength of family bonds. Join the journey of discovering the joys and challenges that make every family unique.",
    ISBN: "978-1234567891",
    publisher: "Warmth Horizon Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 8,
    title: "A Weekend in Colorado",
    author: "Anita Crawford",
    image: require("@/assets/images/a weekend in colorado.jpeg"),
    language: "English",
    category: "Family",
    description:
      "A Weekend in Colorado is an inspiring tale of adventure, connection, and the beauty of family togetherness. Anita Crawford invites you to explore the heartfelt memories created during an unforgettable journey through the stunning landscapes of Colorado.",
    ISBN: "978-9876543210",
    publisher: "Scenic Tales Publishing",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 9,
    title: "Lovely Family",
    author: "Olivia Wilson",
    image: require("@/assets/images/lovely family.jpeg"),
    language: "English",
    category: "Family",
    description:
      "Lovely Family: The Most Precious Treasure is a heartfelt story that celebrates the simple yet profound joys of family life. Olivia Wilson beautifully captures the essence of love, laughter, and the enduring bonds that make a family truly special.",
    ISBN: "978-1122334455",
    publisher: "Golden Heart Publications",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 10,
    title: "Ancient Egyptian Myths",
    author: "Catherine Chambers",
    image: require("@/assets/images/ancient egyptian myths.jpeg"),
    language: "English",
    category: "History",
    description:
      "Ancient Egyptian Myths delves into the fascinating world of gods, pharaohs, creation, and the afterlife. Catherine Chambers brings the ancient tales to life, offering a captivating exploration of Egypt’s rich mythological heritage.",
    ISBN: "978-9876543210",
    publisher: "Golden Heart Publications",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 11,
    title: "Be Fine",
    author: "Dr. Lisa Leslie-Williams",
    image: require("@/assets/images/be fine.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "Be Fine offers a drug-free prescription to age well, beat bulge, and stop disease. Dr. Lisa Leslie-Williams provides practical advice, inspiring tips, and over 40 delicious recipes to guide readers toward a healthier lifestyle.",
    ISBN: "978-1234567890",
    publisher: "Wellness Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 12,
    title: "Carrie Anne's World",
    author: "Mark Whiteway",
    image: require("@/assets/images/carrie annes world.jpeg"),
    language: "English",
    category: "Science Fiction & Fantasy",
    description:
      "Carrie Anne's World is an extraordinary odyssey through space and time. Mark Whiteway weaves a mesmerizing tale of adventure, discovery, and the boundless possibilities of the universe, making it a must-read for fans of speculative fiction.",
    ISBN: "978-0987654321",
    publisher: "Cosmic Tales Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 13,
    title: "Detritus",
    author: "Jane Doe",
    image: require("@/assets/images/detritus.jpeg"),
    language: "English",
    category: "Mystery & Thriller",
    description:
      "Detritus is a gripping mystery novel that delves into the dark secrets of a small town. Jane Doe masterfully crafts a tale of suspense, intrigue, and unexpected twists that will keep readers on the edge of their seats.",
    ISBN: "978-1122334455",
    publisher: "Mystery House",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 14,
    title: "Dictionary of Ancient Egypt",
    author: "John Baines and Jaromir Malek",
    image: require("@/assets/images/dictionary of ancient egypt.jpeg"),
    language: "English",
    category: "History",
    description:
      "Dictionary of Ancient Egypt provides a comprehensive guide to the fascinating world of ancient Egypt. John Baines and Jaromir Malek offer detailed entries on the people, places, and artifacts that shaped this remarkable civilization.",
    ISBN: "978-0192802934",
    publisher: "Oxford University Press",
    publishingNumber: "2nd Edition",
    publishingYear: 2023,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 15,
    title: "Egyptian History",
    author: "John Baines and Jaromir Malek",
    image: require("@/assets/images/egyptian history.jpeg"),
    language: "English",
    category: "History",
    description:
      "Egyptian History provides a comprehensive guide to the fascinating world of ancient Egypt. John Baines and Jaromir Malek offer detailed entries on the people, places, and artifacts that shaped this remarkable civilization.",
    ISBN: "978-0192802934",
    publisher: "Oxford University Press",
    publishingNumber: "2nd Edition",
    publishingYear: 2023,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 16,
    title: "Fighting for Family",
    author: "Jane Smith",
    image: require("@/assets/images/fighting for family.jpeg"),
    language: "English",
    category: "Drama",
    description:
      "Fighting for Family is a heart-wrenching drama that explores the complexities of familial relationships. Jane Smith weaves a powerful narrative about love, sacrifice, and the lengths one will go to protect their loved ones.",
    ISBN: "978-1234567891",
    publisher: "Family Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 17,
    title: "Final Imaginary Eclipse",
    author: "Alex Johnson",
    image: require("@/assets/images/final imaginary eclipse.jpeg"),
    language: "English",
    category: "Science Fiction & Fantasy",
    description:
      "Final Imaginary Eclipse is a thrilling science fiction novel that takes readers on an epic journey through space and time. Alex Johnson masterfully blends adventure, mystery, and the unknown in a story that will captivate fans of speculative fiction.",
    ISBN: "978-9876543210",
    publisher: "Galactic Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 18,
    title: "French Revolution",
    author: "Marie Dupont",
    image: require("@/assets/images/french revolution.jpeg"),
    language: "English",
    category: "History",
    description:
      "French Revolution provides an in-depth look at one of the most significant events in world history. Marie Dupont offers a detailed account of the causes, key figures, and lasting impacts of the revolution, making it an essential read for history enthusiasts.",
    ISBN: "978-1122334456",
    publisher: "Historical Insights Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 19,
    title: "Game of Masks",
    author: "Emily Carter",
    image: require("@/assets/images/game of masks.jpeg"),
    language: "English",
    category: "Mystery & Thriller",
    description:
      "Game of Masks is a captivating mystery novel that delves into a world of secrets and deception. Emily Carter weaves a thrilling tale of intrigue and suspense, where every character hides behind a mask, and nothing is as it seems.",
    ISBN: "978-2233445566",
    publisher: "Thriller House",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 20,
    title: "Gem of the Ocean",
    author: "August Wilson",
    image: require("@/assets/images/gem of the ocean.jpeg"),
    language: "English",
    category: "Drama",
    description:
      "Gem of the Ocean is a powerful drama that explores themes of freedom, redemption, and the African American experience. August Wilson masterfully crafts a narrative that is both poignant and thought-provoking, making it a must-read for fans of literary drama.",
    ISBN: "978-9876543211",
    publisher: "Dramatic Works Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 21,
    title: "Good Selfie",
    author: "Turia Pitt",
    image: require("@/assets/images/good selfie.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "Good Selfie is an inspiring self-help book by Turia Pitt. It offers practical advice, motivational stories, and actionable steps to help readers build confidence, overcome challenges, and live their best lives.",
    ISBN: "978-0987654322",
    publisher: "Inspiration Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 22,
    title: "Heir of the Gift",
    author: "John Doe",
    image: require("@/assets/images/heir of the gift.jpeg"),
    language: "English",
    category: "Science Fiction & Fantasy",
    description:
      "Heir of the Gift is an enchanting fantasy novel that takes readers on a magical journey through a world of wonder and adventure. John Doe masterfully weaves a tale of destiny, power, and the enduring struggle between good and evil.",
    ISBN: "978-1234567892",
    publisher: "Fantasy Realm Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 23,
    title: "How to Build Your Self-Esteem",
    author: "Jane Smith",
    image: require("@/assets/images/how to build your self esteem.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "How to Build Your Self-Esteem is a practical guide that offers strategies and tips to help readers boost their confidence and self-worth. Jane Smith provides actionable advice and exercises to empower individuals to believe in themselves and achieve their goals.",
    ISBN: "978-1122334457",
    publisher: "Empowerment Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 24,
    title: "How to Help Yourself with Self-Help",
    author: "John Doe",
    image: require("@/assets/images/How to help yourself with self-help.jpeg"),
    language: "English",
    category: "Self-Help",
    description:
      "How to Help Yourself with Self-Help is a comprehensive guide that explores various self-help techniques and strategies. John Doe provides insightful advice and practical steps to help readers take control of their lives and achieve personal growth.",
    ISBN: "978-2233445567",
    publisher: "Self-Improvement Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 25,
    title: "Paul Rix Reuc",
    author: "Author Name",
    image: require("@/assets/images/paul rix reuc.jpeg"),
    language: "English",
    category: "Biography",
    description:
      "Paul Rix Reuc is an inspiring biography that delves into the life and achievements of Paul Rix Reuc. The author provides a detailed account of his journey, challenges, and successes.",
    ISBN: "978-1234567893",
    publisher: "Biography Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 26,
    title: "Journey to the Stars",
    author: "Emily Carter",
    image: require("@/assets/images/journey to the stars.jpeg"),
    language: "English",
    category: "Science Fiction",
    description:
      "Journey to the Stars is a captivating science fiction novel that takes readers on an epic adventure through space. Emily Carter masterfully blends science and imagination in a story that will enthrall fans of the genre.",
    ISBN: "978-2233445568",
    publisher: "Galactic Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 27,
    title: "The Girl Who Said No",
    author: "Jane Doe",
    image: require("@/assets/images/the girl who said no.jpeg"),
    language: "English",
    category: "Drama",
    description:
      "The Girl Who Said No is a powerful drama that explores themes of courage, resilience, and the fight for justice. Jane Doe weaves a compelling narrative that will resonate with readers.",
    ISBN: "978-1122334458",
    publisher: "Drama House",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 28,
    title: "The Black Night",
    author: "John Smith",
    image: require("@/assets/images/the black night.jpeg"),
    language: "English",
    category: "Mystery & Thriller",
    description:
      "The Black Night is a gripping mystery novel that delves into a world of secrets and suspense. John Smith crafts a thrilling tale that will keep readers on the edge of their seats.",
    ISBN: "978-2233445569",
    publisher: "Thriller Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 29,
    title: "Magical Kingdom",
    author: "Alice Johnson",
    image: require("@/assets/images/magical kingdom.webp"),
    language: "English",
    category: "Science Fiction & Fantasy",
    description:
      "Magical Kingdom is an enchanting fantasy novel that takes readers on a magical journey through a world of wonder and adventure. Alice Johnson masterfully weaves a tale of destiny and magic.",
    ISBN: "978-1234567894",
    publisher: "Fantasy Realm Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 30,
    title: "The Outer Space",
    author: "Mark Whiteway",
    image: require("@/assets/images/the outer space.jpeg"),
    language: "English",
    category: "Science Fiction",
    description:
      "The Outer Space is a thrilling science fiction novel that explores the mysteries of the universe. Mark Whiteway takes readers on an epic journey through space and time.",
    ISBN: "978-2233445570",
    publisher: "Galactic Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 31,
    title: "The Noise of War",
    author: "Robert Brown",
    image: require("@/assets/images/the noise of war.jpeg"),
    language: "English",
    category: "Historical Fiction",
    description:
      "The Noise of War is a gripping historical fiction novel that delves into the chaos and turmoil of war. Robert Brown masterfully portrays the human experience amidst the backdrop of conflict.",
    ISBN: "978-2233445571",
    publisher: "Historical Fiction Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 32,
    title: "The Nobel Family",
    author: "Sarah Green",
    image: require("@/assets/images/the nobel family.jpeg"),
    language: "English",
    category: "Drama",
    description:
      "The Nobel Family is a compelling drama that explores the complexities of family dynamics and the pursuit of excellence. Sarah Green weaves a powerful narrative about love, ambition, and legacy.",
    ISBN: "978-2233445572",
    publisher: "Drama House",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 33,
    title: "The Leaf Thief",
    author: "Emily Brown",
    image: require("@/assets/images/the leaf thief.jpeg"),
    language: "English",
    category: "Children's Book",
    description:
      "The Leaf Thief is a delightful children's book that tells the story of a mischievous squirrel and his adventures in the forest. Emily Brown crafts a charming tale that will captivate young readers.",
    ISBN: "978-2233445573",
    publisher: "Children's Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 34,
    title: "The Greeks",
    author: "Michael Johnson",
    image: require("@/assets/images/the greeks.jpeg"),
    language: "English",
    category: "History",
    description:
      "The Greeks is a comprehensive history book that explores the rich and fascinating history of ancient Greece. Michael Johnson provides detailed insights into the culture, politics, and achievements of the Greek civilization.",
    ISBN: "978-2233445574",
    publisher: "Historical Insights Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 35,
    title: "You're Worth Taking Care Of",
    author: "Jane Smith",
    image: require("@/assets/images/you're worth taking care of.png"),
    language: "English",
    category: "Self-Help",
    description:
      "You're Worth Taking Care Of is an empowering self-help book that offers practical advice and strategies for self-care and personal growth. Jane Smith provides readers with the tools they need to prioritize their well-being and live a fulfilling life.",
    ISBN: "978-2233445575",
    publisher: "Self-Improvement Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
  {
    id: 36,
    title: "Unscripted",
    author: "John Doe",
    image: require("@/assets/images/unscripted.jpeg"),
    language: "English",
    category: "Biography",
    description:
      "Unscripted is an inspiring biography that delves into the life and achievements of a remarkable individual. John Doe provides a detailed account of their journey, challenges, and successes.",
    ISBN: "978-2233445576",
    publisher: "Biography Press",
    publishingNumber: "1st Edition",
    publishingYear: 2024,
    url: "https://reallygreatsite.com",
    price: 20,
  },
];

export const trendingBooks = [
  {
    id: 37,
    title: "Creation of Depth",
    author: "Alex Harper",
    image: require("@/assets/images/creation of depth.png"),
    language: "English",
    category: "Art, Design, Philosophy",
    description:
      "Creation of Depth is a stunning exploration of artistic and conceptual layers, blending design principles with philosophical reflections. Alex Harper masterfully navigates the interplay of depth and perception, bringing to life a visually and intellectually captivating journey.",
    ISBN: "978-9876543210",
    publisher: "Deep Insights Publishing",
    publishingNumber: "2nd Edition",
    publishingYear: 2022,
    url: "https://drive",
    price: 20,
  },
  {
    id: 38,
    title: "Meet Me at the Lake",
    author: "Carley Fortune",
    image: require("@/assets/images/meet me at the lake.png"),
    language: "English",
    category: "Romance, Contemporary Fiction",
    description:
      "Meet Me at the Lake is a heartfelt romance novel about second chances, love, and self-discovery. Carley Fortune beautifully weaves a story set against the backdrop of a serene lake, where two souls reconnect and confront the complexities of their past. With vivid storytelling and emotional depth, this novel is a must-read for fans of contemporary romance.",
    ISBN: "978-1122334455",
    publisher: "Sunset Horizon Publishing",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://drive",
    price: 20,
  },
  {
    id: 39,
    title: "Queenie",
    author: "Candice Carty-Williams",
    image: require("@/assets/images/queenie.png"),
    language: "English",
    category: "Contemporary Fiction, Coming-of-Age",
    description:
      '"Queenie" is a powerful and thought-provoking novel that explores identity, mental health, and the complexities of navigating relationships in the modern world. Candice Carty-Williams weaves a poignant and witty story centered around Queenie Jenkins, a young woman grappling with her sense of self and her place in the world.',
    ISBN: "978-1409180074",
    publisher: "Orion Publishing Group",
    publishingNumber: "1st Edition",
    publishingYear: 2019,
    url: "https://drive",
    price: 20,
  },
  {
    id: 40,
    title: "Out of the Belly",
    author: "Jannie V. Cudjo-Moore",
    image: require("@/assets/images/out of the belly.png"),
    language: "English",
    category: "Spiritual, Inspirational",
    description:
      '"Out of the Belly" is an inspirational book that delves into themes of faith, redemption, and resilience. Through vivid imagery and heartfelt storytelling, Jannie V. Cudjo-Moore takes readers on a journey of self-discovery and spiritual awakening, offering encouragement and hope for life\'s challenges.',
    ISBN: "978-1234567890",
    publisher: "Hope & Light Publishing",
    publishingNumber: "1st Edition",
    publishingYear: 2022,
    url: "https://drive",
    price: 20,
  },
  {
    id: 41,
    title: "Mother Island",
    author: "Jamie Figueroa",
    image: require("@/assets/images/motherisland.png"),
    language: "English",
    category: "Drama",
    description:
      "Mother Island is a poetic and evocative narrative that delves into themes of identity, belonging, and the unbreakable bonds of family. Through vivid storytelling and heartfelt emotion, Jamie Figueroa presents a story of a daughter's journey to reclaim her heritage and find her true self.",
    ISBN: "978-1234567890",
    publisher: "Azure Horizon Press",
    publishingNumber: "1st Edition",
    publishingYear: 2023,
    url: "https://drive.google.com/file/d/1rtnWmZpzu3kfba-BEBXaGYgiGFKULBgt/view?usp=drive_link",
    price: 20,
  },
];

export const reviews = [
  {
    username: "Laurence Ashraf",
    review:
      "Full of twists and turns! Just when I thought I had it figured out, the plot surprised me again.",
    rating: 5,
    cover: require("@/assets/images/out of the belly.png"),
  },
  {
    username: "Laurence Ashraf",
    review: "This book is amazing! I couldn't put it down.",
    rating: 5,
    cover: require("@/assets/images/the dance of destiny.png"),
  },
  {
    username: "Laurence Ashraf",
    review:
      "Heartwarming and emotional. The love story was beautifully written and stayed with me long after I finished.",
    rating: 5,
    cover: require("@/assets/images/meet me at the lake.png"),
  },
  {
    username: "Laurence Ashraf",
    review:
      "A magical journey from start to finish! The world-building is phenomenal, and the characters feel so real.",
    rating: 5,
    cover: require("@/assets/images/creation of depth.png"),
  },
];
